apiVersion: v1
kind: Service
metadata:
  name: openstory
  labels:
    app.kubernetes.io/name: openstory
spec:
  selector:
    app.kubernetes.io/name: openstory
  ports:
    - name: http
      port: 3002
      targetPort: http
