[package]
name = "arena"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
argon2 = "0.5"
async-trait = "0.1"
axum = { version = "0.8" }
axum-extra = { version = "0.10", features = ["cookie-signed"] }
bollard = "0.19"
chrono = { version = "0.4", features = ["serde"] }
rand = "0.8"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
rusqlite = { version = "0.35", features = ["bundled"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
time = "0.3"
tokio = { version = "1", features = ["full"] }
toml = "0.8"

[dev-dependencies]
futures-util = "0.3.34"
tower = { version = "0.5", features = ["util"] }
