import { chromium } from "playwright";
const S = "/tmp/claude-1000/-home-max-projects-OpenStory/0375729d-4f5f-4043-bf1e-71a8ad37a187/scratchpad";
const b = await chromium.launch({ executablePath: `${S}/chrome-linux/chrome`, headless: true, args: ["--no-sandbox","--disable-dev-shm-usage","--disable-gpu"] });
const p = await b.newPage({ viewport: { width: 1500, height: 950 } });
p.on("pageerror", e => console.log("PAGEERR:", e.message));
await p.goto("http://127.0.0.1:5173/#/canvas",{waitUntil:"networkidle"}); await p.waitForTimeout(1500);
await p.getByRole("button",{name:"scatter",exact:true}).first().click(); await p.waitForTimeout(1800);
console.log("scatter legend present:", !!(await p.$('[data-testid="agent-legend"]')));
console.log("scatter legend text:", await p.$eval('[data-testid="agent-legend"]', e=>e.innerText.replace(/\n/g,' ')).catch(()=>"(none)"));
await p.screenshot({path:`${S}/rev-legend-scatter.png`});
await p.getByRole("button",{name:"gantt",exact:true}).first().click(); await p.waitForTimeout(1500);
console.log("gantt legend text:", await p.$eval('[data-testid="agent-legend"]', e=>e.innerText.replace(/\n/g,' ')).catch(()=>"(none)"));
await p.screenshot({path:`${S}/rev-legend-gantt.png`});
console.log("done");
await b.close();
