import { chromium } from "playwright";
const S = "/tmp/claude-1000/-home-max-projects-OpenStory/0375729d-4f5f-4043-bf1e-71a8ad37a187/scratchpad";
const b = await chromium.launch({ executablePath: `${S}/chrome-linux/chrome`, headless: true, args: ["--no-sandbox","--disable-dev-shm-usage","--disable-gpu"] });
const p = await b.newPage({ viewport: { width: 1500, height: 950 } });
p.on("pageerror", e => console.log("PAGEERR:", e.message.slice(0,140)));
await p.goto("http://127.0.0.1:5173/#/lab",{waitUntil:"networkidle"}); await p.waitForTimeout(2500);
const cards = await p.$$eval('[data-candidate]', els=>els.length);
const first = await p.$$eval('[data-candidate]', els=>els.slice(0,3).map(e=>e.querySelector('.font-semibold')?.textContent.trim()));
console.log("candidate cards:", cards, "· top 3:", JSON.stringify(first));
await p.screenshot({path:`${S}/rev-lab.png`});
console.log("saved");
await b.close();
