"""Build a personalised "OpenStory, exercised" report from YOUR real data.

Sibling of build_prompt_library.py. Where the prompt library shows *illustrative*
examples, this renders the *real* output of running each of the twelve
openstory-skills against your live store — one section per skill, charted with
the same vocabulary (stats / bars / table / timeline / …) and theme.

Data in, report out. The numbers live in a JSON file (gathered by querying the
OpenStory MCP/REST API — see scripts/, or the fan-out that produced
drafts/skill_report_data.json); this script only renders. That keeps it a pure,
re-runnable transform: regenerate the page/PDF any time the data file changes.

    --data PATH   the report data JSON (default: drafts/skill_report_data.json)
    --html PATH   the report web page
    --pdf  PATH   print-ready PDF (via headless Chrome)
    --theme NAME  palette (default: georgetown)
    --test        self-checks against a tiny fixture

Data JSON shape:
    {
      "title": "...", "subtitle": "...", "window": "last 30 days",
      "sections": [
        {"ix":"01","color":"blue","title":"/cost · what your sessions cost",
         "prompt":"What have my agent sessions cost me?",
         "source":"token_usage + daily_token_usage",
         "viz":[ <block>, ... ]}
      ]
    }
Each <block> is exactly a build_prompt_library viz block (stats/bars/table/…).
"""

import argparse
import json
import sys
from pathlib import Path

# Reuse the chart engine + theme + PDF renderer from the sibling generator.
sys.path.insert(0, str(Path(__file__).resolve().parent))
from build_prompt_library import _block, _e, root_css, _CSS, THEMES, chrome_pdf, leakage  # noqa: E402

_COLORS = {"blue", "cyan", "purple", "green", "orange", "red"}

_PAGE = """<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="{fontlink}" rel="stylesheet">
<style>{css}</style></head>
<body><div class="wrap">
  <header>
    <p class="eyebrow">OpenStory · your data</p>
    <h1>{title_html}</h1>
    <p class="sub">{subtitle}</p>
    <div class="howto"><strong>How this was made:</strong> each section is the real
      output of one of the twelve <code>openstory-skills</code> run against your live
      store{window_html} — the same reports, charted from your own history. Names of
      collaborators are shown as roles; secrets are never included.</div>
  </header>
{body}
  <div class="draftnote">Generated by <span class="mono">scripts/build_skill_report.py</span> from
    <span class="mono">drafts/skill_report_data.json</span> — re-run any time to refresh.</div>
  <footer>OpenStory · a mirror, not a leash.</footer>
</div></body></html>"""


def render_html(data: dict, theme: str = "georgetown") -> str:
    if theme not in THEMES:
        raise ValueError(f"unknown theme {theme!r}; choose from {list(THEMES)}")
    secs = []
    for s in data["sections"]:
        if s.get("color") not in _COLORS:
            raise ValueError(f"section {s.get('ix')!r}: color must be one of {_COLORS}")
        viz = "".join(_block(b) for b in s["viz"])
        secs.append(
            f'<section class="{s["color"]}"><div class="sechead">'
            f'<span class="ix">{_e(s["ix"])}</span><h2>{_e(s["title"])}</h2></div>'
            f'<p class="why">{_e(s.get("prompt", ""))}</p>'
            f'<div class="viz">{viz}<div class="src">{_e(s.get("source", ""))}</div></div></section>'
        )
    title = data.get("title", "Your OpenStory")
    grad = data.get("title_grad", "")
    title_html = _e(title)
    if grad and grad in title:
        title_html = _e(title).replace(_e(grad), f'<span class="grad">{_e(grad)}</span>', 1)
    window = data.get("window", "")
    window_html = f' over <strong>{_e(window)}</strong>' if window else ""
    return _PAGE.format(
        css=root_css(theme) + _CSS, fontlink=THEMES[theme]["link"],
        title=_e(title), title_html=title_html, subtitle=_e(data.get("subtitle", "")),
        window_html=window_html, body="\n".join(secs),
    )


def run_tests() -> None:
    print("Running tests...")
    fixture = {
        "title": "Your work, measured", "title_grad": "measured",
        "subtitle": "A report from your own history.", "window": "last 30 days",
        "sections": [
            {"ix": "01", "color": "blue", "title": "/cost · what your sessions cost",
             "prompt": "What have my agent sessions cost me?", "source": "token_usage",
             "viz": [{"type": "stats", "items": [{"num": "12.4M", "label": "tokens", "accent": True},
                                                 {"num": "$58", "label": "est. cost"}]},
                     {"type": "note", "text": "**Cache** saved most of the spend."}]},
            {"ix": "02", "color": "green", "title": "/coach · how you work",
             "prompt": "Honest feedback?", "source": "session_patterns",
             "viz": [{"type": "bars", "title": "themes", "items": [{"label": "docs", "bar": 60, "val": "60%"}]}]},
        ],
    }
    h = render_html(fixture)
    assert h.startswith("<!doctype html>") and h.rstrip().endswith("</html>")
    assert h.count("<section") == 2, "one section per skill"
    assert "12.4M" in h and "$58" in h, "real numbers rendered"
    assert '<span class="grad">measured</span>' in h, "title gradient span"
    for klass in ("vstats", "vbars", "vnote"):
        assert klass in h, f"missing chart primitive {klass}"
    assert ":root{" in h and "--bg:" in h, "theme tokens present"
    # color validation
    try:
        render_html({"sections": [{"ix": "x", "color": "teal", "title": "t", "viz": []}]})
        raise AssertionError("should reject unknown color")
    except ValueError:
        pass
    assert not leakage(h), f"leakage: {leakage(h)}"
    print(f"  OK: report renders {h.count('<section')} sections, real numbers, themed, no leakage")
    print("\nAll tests passed.")


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--data", metavar="PATH", default="drafts/skill_report_data.json")
    ap.add_argument("--html", metavar="PATH")
    ap.add_argument("--pdf", metavar="PATH")
    ap.add_argument("--theme", default="georgetown", choices=list(THEMES))
    ap.add_argument("--test", action="store_true")
    args = ap.parse_args()
    if args.test:
        run_tests(); sys.exit(0)
    if not (args.html or args.pdf):
        ap.error("pass --html PATH and/or --pdf PATH (or --test)")
    data = json.loads(Path(args.data).read_text(encoding="utf-8"))
    leaks = leakage(json.dumps(data))
    if leaks:
        ap.error(f"refusing to render — possible secrets in data: {leaks}")
    html = render_html(data, args.theme)
    if args.html:
        Path(args.html).write_text(html, encoding="utf-8"); print(f"Wrote {args.html} [{args.theme}]")
    if args.pdf:
        chrome_pdf(html, args.pdf); print(f"Wrote {args.pdf} [{args.theme}]")
