//! Live writer for the nats-server account config (Phase 5.4).
//!
//! `AccountConfigWriter` holds the in-memory list of `AccountSpec`s and
//! persists them to a conf file on disk. Reloading nats-server so it picks
//! up the new accounts is a separate concern — exposed as the
//! [`NatsReloader`] trait so tests can use docker-exec and prod can use a
//! POSIX SIGHUP or a NATS control subject.
//!
//! The split-of-concerns mirrors PR #58: pure state mutation + serialization
//! in one type, side-effects (process signaling) in another. Lets the
//! writer be unit-tested without spinning up NATS or a container.

use std::path::PathBuf;
use std::sync::Mutex;

use anyhow::{anyhow, Result};
use async_trait::async_trait;

use open_story_bus::accounts::{render_accounts_block, AccountSpec};

/// Mutates and persists the nats-server account config.
///
/// Owns the list of accounts in memory; on `persist()`, writes the
/// `static_prefix` (listen/jetstream/leafnodes) followed by the rendered
/// `accounts { ... }` block to `conf_path`. Atomic via tmpfile + rename.
pub struct AccountConfigWriter {
    conf_path: PathBuf,
    static_prefix: String,
    state: Mutex<Vec<AccountSpec>>,
}

impl AccountConfigWriter {
    pub fn new(
        conf_path: PathBuf,
        static_prefix: impl Into<String>,
        initial: Vec<AccountSpec>,
    ) -> Self {
        Self {
            conf_path,
            static_prefix: static_prefix.into(),
            state: Mutex::new(initial),
        }
    }

    /// Render the current in-memory state as a complete nats-server conf.
    pub fn current_config(&self) -> String {
        let state = self.state.lock().unwrap();
        let block = render_accounts_block(&state);
        format!("{}\n{}", self.static_prefix, block)
    }

    /// Write the current state to disk atomically (tmpfile + rename).
    /// The on-disk file is replaced in one step, so nats-server never sees
    /// a partially-written conf.
    pub fn persist(&self) -> Result<()> {
        let body = self.current_config();
        let parent = self
            .conf_path
            .parent()
            .ok_or_else(|| anyhow!("conf path has no parent: {:?}", self.conf_path))?;
        std::fs::create_dir_all(parent)?;
        let tmp = parent.join(format!(
            ".{}.tmp",
            self.conf_path
                .file_name()
                .and_then(|s| s.to_str())
                .unwrap_or("nats-conf")
        ));
        std::fs::write(&tmp, body)?;
        std::fs::rename(&tmp, &self.conf_path)?;
        Ok(())
    }
}

/// Trait for "tell nats-server to reread its conf." Implementations: SIGHUP
/// for a locally-owned process, docker-exec for a testcontainer, an HTTP
/// or NATS control subject in a managed deployment.
#[async_trait]
pub trait NatsReloader: Send + Sync {
    async fn reload(&self) -> Result<()>;
}

/// No-op reloader for tests that only check persist() semantics.
pub struct NoopReloader;

#[async_trait]
impl NatsReloader for NoopReloader {
    async fn reload(&self) -> Result<()> {
        Ok(())
    }
}

/// Shell-command reloader. Production default is `pkill -HUP nats-server`,
/// configurable via `Config::nats_reload_command`. Failures (non-zero exit,
/// command not found) bubble up as `Err` so the handler can surface to the
/// operator. Stdout/stderr are captured but discarded — the operator should
/// look at nats-server logs for the actual outcome.
pub struct ShellCommandReloader {
    pub command: String,
}

#[async_trait]
impl NatsReloader for ShellCommandReloader {
    async fn reload(&self) -> Result<()> {
        let output = tokio::process::Command::new("sh")
            .arg("-c")
            .arg(&self.command)
            .output()
            .await?;
        if !output.status.success() {
            anyhow::bail!(
                "reload command `{}` exited with status {}",
                self.command,
                output.status
            );
        }
        Ok(())
    }
}

/// Static prefix written ahead of the `accounts { ... }` block. Includes
/// the listen socket and JetStream store dir — enough for nats-server to
/// boot. Operators who need leafnodes/clusters/TLS should override the
/// prefix path and manage the file themselves; for local dev this default
/// gets you running with `nats-server -c <managed-conf-path>`.
pub const DEFAULT_NATS_STATIC_PREFIX: &str = "\
# Generated by OpenStory AccountConfigWriter. DO NOT EDIT —
# this file is overwritten on every POST /api/admin/share-with-person.
listen: 0.0.0.0:4222
jetstream {
  store_dir: \"./data/nats-jetstream\"
}";

#[cfg(test)]
mod tests {
    use super::*;
    use open_story_bus::accounts::{AccountSpec, UserSpec};
    use tempfile::TempDir;

    fn person(name: &str, user: &str) -> AccountSpec {
        AccountSpec {
            name: name.into(),
            users: vec![UserSpec {
                user: user.into(),
                password: format!("{user}-secret"),
                permissions: None,
            }],
            exports: vec![],
            imports: vec![],
        }
    }

    fn writer_in(tmp: &TempDir, initial: Vec<AccountSpec>) -> AccountConfigWriter {
        AccountConfigWriter::new(
            tmp.path().join("nats-server.conf"),
            "listen: 0.0.0.0:4222",
            initial,
        )
    }

    #[test]
    fn default_prefix_quotes_relative_store_dir() {
        // nats-server's conf parser reads an unquoted leading `.` as a
        // malformed float ("Parse error: 'Floats must start with a digit'")
        // and refuses to boot. Relative paths must be quoted.
        assert!(DEFAULT_NATS_STATIC_PREFIX.contains("store_dir: \"./data/nats-jetstream\""));
    }

    #[test]
    fn persist_writes_the_current_config_atomically() {
        let tmp = tempfile::tempdir().unwrap();
        let writer = writer_in(&tmp, vec![person("PERSON_MAX", "max"), person("PERSON_KATIE", "katie")]);
        writer.persist().unwrap();

        let on_disk = std::fs::read_to_string(tmp.path().join("nats-server.conf")).unwrap();
        assert_eq!(on_disk, writer.current_config());
    }

    #[test]
    fn persist_emits_the_static_prefix_before_accounts() {
        let tmp = tempfile::tempdir().unwrap();
        let writer = AccountConfigWriter::new(
            tmp.path().join("nats-server.conf"),
            "listen: 0.0.0.0:4222\njetstream { store_dir: /var/lib/nats }",
            vec![person("PERSON_MAX", "max")],
        );
        writer.persist().unwrap();

        let on_disk = std::fs::read_to_string(tmp.path().join("nats-server.conf")).unwrap();
        // Prefix appears before the accounts block.
        let listen_idx = on_disk.find("listen:").expect("listen present");
        let accounts_idx = on_disk.find("accounts {").expect("accounts present");
        assert!(listen_idx < accounts_idx);
        // Both required pieces of the static prefix landed.
        assert!(on_disk.contains("jetstream { store_dir:"));
    }
}
